"""add_loyalty_tables

Revision ID: b3bff35888f8
Revises: 918418aae322
Create Date: 2026-05-09 20:52:21.600641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bff35888f8'
down_revision: Union[str, None] = '918418aae322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('points_per_1000', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rupee_value_per_point', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_redeem_points', sa.Integer(), nullable=False),
    sa.Column('max_redeem_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_configs_id'), 'loyalty_configs', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_configs_store_id'), 'loyalty_configs', ['store_id'], unique=True)
    op.create_table('loyalty_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('earn', 'redeem', 'adjust', 'expire', name='loyalty_event_type'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_ledger_created_at'), 'loyalty_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_loyalty_ledger_customer_id'), 'loyalty_ledger', ['customer_id'], unique=False)
    op.create_index('ix_loyalty_ledger_customer_store', 'loyalty_ledger', ['customer_id', 'store_id'], unique=False)
    op.create_index(op.f('ix_loyalty_ledger_id'), 'loyalty_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_ledger_store_id'), 'loyalty_ledger', ['store_id'], unique=False)
    op.drop_index('idx_txn_invoice_number', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_txn_invoice_number', 'transactions', ['invoice_number'], unique=True)
    op.drop_index(op.f('ix_loyalty_ledger_store_id'), table_name='loyalty_ledger')
    op.drop_index(op.f('ix_loyalty_ledger_id'), table_name='loyalty_ledger')
    op.drop_index('ix_loyalty_ledger_customer_store', table_name='loyalty_ledger')
    op.drop_index(op.f('ix_loyalty_ledger_customer_id'), table_name='loyalty_ledger')
    op.drop_index(op.f('ix_loyalty_ledger_created_at'), table_name='loyalty_ledger')
    op.drop_table('loyalty_ledger')
    op.drop_index(op.f('ix_loyalty_configs_store_id'), table_name='loyalty_configs')
    op.drop_index(op.f('ix_loyalty_configs_id'), table_name='loyalty_configs')
    op.drop_table('loyalty_configs')
    # ### end Alembic commands ###
