"""align_schema

Revision ID: d6433dc450d4
Revises: e135c148c311
Create Date: 2026-05-06 22:44:55.628746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6433dc450d4'
down_revision: Union[str, None] = 'e135c148c311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_store_id'), 'audit_log', ['store_id'], unique=False)
    op.create_foreign_key(None, 'audit_log', 'stores', ['store_id'], ['id'])
    op.alter_column('customers', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_customers_store_id'), 'customers', ['store_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'stores', ['store_id'], ['id'])
    op.alter_column('inventory_pieces', 'status',
               existing_type=mysql.VARCHAR(length=30),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'inventory_pieces', 'karigars', ['karigar_id'], ['id'])
    op.alter_column('order_steps', 'step_order',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('order_steps', 'is_done',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('order_steps', 'is_bypassed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_os_order', table_name='order_steps')
    op.create_index(op.f('ix_order_steps_id'), 'order_steps', ['id'], unique=False)
    op.create_index(op.f('ix_order_steps_order_id'), 'order_steps', ['order_id'], unique=False)
    op.create_foreign_key(None, 'order_steps', 'karigars', ['karigar_id'], ['id'])
    op.create_foreign_key(None, 'order_steps', 'orders', ['order_id'], ['id'])
    op.create_index(op.f('ix_orders_karigar_id'), 'orders', ['karigar_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'karigars', ['karigar_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'workflow_templates', ['workflow_template_id'], ['id'])
    op.drop_constraint('piece_lifecycle_events_ibfk_2', 'piece_lifecycle_events', type_='foreignkey')
    op.create_foreign_key(None, 'piece_lifecycle_events', 'inventory_pieces', ['piece_id'], ['id'], ondelete='CASCADE')
    op.alter_column('stock_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_stock_categories_id'), 'stock_categories', ['id'], unique=False)
    # MySQL requires dropping FK constraints before dropping their backing indexes.
    # stock_items_ibfk_1 backs ix_stock_items_store_id; stock_movements_ibfk_1 backs ix_stock_movements_item_id.
    op.drop_constraint('stock_items_ibfk_1', 'stock_items', type_='foreignkey')
    op.drop_index('ix_stock_items_store_id', table_name='stock_items')
    op.create_foreign_key(None, 'stock_items', 'stores', ['store_id'], ['id'])
    op.drop_constraint('stock_movements_ibfk_1', 'stock_movements', type_='foreignkey')
    op.drop_index('ix_stock_movements_item_id', table_name='stock_movements')
    op.create_foreign_key(None, 'stock_movements', 'stock_items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'stock_movements', 'users', ['created_by'], ['id'])
    op.alter_column('stores', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stores', 'invoice_seq_current',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('stores', 'default_hsn_gold',
               existing_type=mysql.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('stores', 'default_hsn_silver',
               existing_type=mysql.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('stores', 'default_hsn_making',
               existing_type=mysql.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('stores', 'default_hsn_diamond',
               existing_type=mysql.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_stores_contact_phone'), 'stores', ['contact_phone'], unique=False)
    op.create_index(op.f('ix_stores_customer_code'), 'stores', ['customer_code'], unique=True)
    op.alter_column('transactions', 'gst_computed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'tax_rate',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'making_tax_rate',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'taxable_value',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'making_charges',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'cgst_amount',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'sgst_amount',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'igst_amount',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'making_cgst',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'making_sgst',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'making_igst',
               existing_type=mysql.FLOAT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('transactions', 'is_interstate',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_txn_invoice_number', table_name='transactions')
    op.create_index(op.f('ix_transactions_invoice_number'), 'transactions', ['invoice_number'], unique=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workflow_template_steps', 'step_order',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_wts_template', table_name='workflow_template_steps')
    op.create_index(op.f('ix_workflow_template_steps_id'), 'workflow_template_steps', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_template_steps_template_id'), 'workflow_template_steps', ['template_id'], unique=False)
    op.create_foreign_key(None, 'workflow_template_steps', 'workflow_templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'workflow_template_steps', 'karigars', ['karigar_id'], ['id'])
    op.alter_column('workflow_templates', 'order_type',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workflow_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('ix_wt_store', table_name='workflow_templates')
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_templates_store_id'), 'workflow_templates', ['store_id'], unique=False)
    op.create_foreign_key(None, 'workflow_templates', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_templates', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_templates_store_id'), table_name='workflow_templates')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.create_index('ix_wt_store', 'workflow_templates', ['store_id'], unique=False)
    op.alter_column('workflow_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('workflow_templates', 'order_type',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'both'"),
               existing_nullable=False)
    op.drop_constraint(None, 'workflow_template_steps', type_='foreignkey')
    op.drop_constraint(None, 'workflow_template_steps', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_template_steps_template_id'), table_name='workflow_template_steps')
    op.drop_index(op.f('ix_workflow_template_steps_id'), table_name='workflow_template_steps')
    op.create_index('ix_wts_template', 'workflow_template_steps', ['template_id'], unique=False)
    op.alter_column('workflow_template_steps', 'step_order',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_invoice_number'), table_name='transactions')
    op.create_index('idx_txn_invoice_number', 'transactions', ['invoice_number'], unique=True)
    op.alter_column('transactions', 'is_interstate',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('transactions', 'making_igst',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('transactions', 'making_sgst',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('transactions', 'making_cgst',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('transactions', 'igst_amount',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('transactions', 'sgst_amount',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('transactions', 'cgst_amount',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('transactions', 'making_charges',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('transactions', 'taxable_value',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('transactions', 'making_tax_rate',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'5'"),
               existing_nullable=True)
    op.alter_column('transactions', 'tax_rate',
               existing_type=mysql.FLOAT(),
               server_default=sa.text("'3'"),
               existing_nullable=True)
    op.alter_column('transactions', 'gst_computed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.drop_index(op.f('ix_stores_customer_code'), table_name='stores')
    op.drop_index(op.f('ix_stores_contact_phone'), table_name='stores')
    op.alter_column('stores', 'default_hsn_diamond',
               existing_type=mysql.VARCHAR(length=10),
               server_default=sa.text("'7102'"),
               existing_nullable=True)
    op.alter_column('stores', 'default_hsn_making',
               existing_type=mysql.VARCHAR(length=10),
               server_default=sa.text("'9988'"),
               existing_nullable=True)
    op.alter_column('stores', 'default_hsn_silver',
               existing_type=mysql.VARCHAR(length=10),
               server_default=sa.text("'7114'"),
               existing_nullable=True)
    op.alter_column('stores', 'default_hsn_gold',
               existing_type=mysql.VARCHAR(length=10),
               server_default=sa.text("'7113'"),
               existing_nullable=True)
    op.alter_column('stores', 'invoice_seq_current',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('stores', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.create_index('ix_stock_movements_item_id', 'stock_movements', ['item_id'], unique=False)
    op.create_index('ix_stock_items_store_id', 'stock_items', ['store_id'], unique=False)
    op.drop_index(op.f('ix_stock_categories_id'), table_name='stock_categories')
    op.alter_column('stock_categories', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.drop_constraint(None, 'piece_lifecycle_events', type_='foreignkey')
    op.create_foreign_key('piece_lifecycle_events_ibfk_2', 'piece_lifecycle_events', 'inventory_pieces', ['piece_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_karigar_id'), table_name='orders')
    op.drop_constraint(None, 'order_steps', type_='foreignkey')
    op.drop_constraint(None, 'order_steps', type_='foreignkey')
    op.drop_index(op.f('ix_order_steps_order_id'), table_name='order_steps')
    op.drop_index(op.f('ix_order_steps_id'), table_name='order_steps')
    op.create_index('ix_os_order', 'order_steps', ['order_id'], unique=False)
    op.alter_column('order_steps', 'is_bypassed',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('order_steps', 'is_done',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.alter_column('order_steps', 'step_order',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_constraint(None, 'inventory_pieces', type_='foreignkey')
    op.alter_column('inventory_pieces', 'status',
               existing_type=mysql.VARCHAR(length=30),
               server_default=sa.text("'in_stock'"),
               existing_nullable=False)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_store_id'), table_name='customers')
    op.alter_column('customers', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_index(op.f('ix_audit_log_store_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    # ### end Alembic commands ###
