"""add_plans_and_subscription

Revision ID: 918418aae322
Revises: 2cabbff59694
Create Date: 2026-05-09 18:23:48.477690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918418aae322'
down_revision: Union[str, None] = '2cabbff59694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_yearly', sa.Float(), nullable=True),
    sa.Column('max_customers', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_stores', sa.Integer(), nullable=True),
    sa.Column('has_girvi', sa.Boolean(), nullable=False),
    sa.Column('has_gst_invoicing', sa.Boolean(), nullable=False),
    sa.Column('has_analytics', sa.Boolean(), nullable=False),
    sa.Column('has_metal_exchange', sa.Boolean(), nullable=False),
    sa.Column('has_inventory', sa.Boolean(), nullable=False),
    sa.Column('has_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('has_bulk_import', sa.Boolean(), nullable=False),
    sa.Column('has_reports_export', sa.Boolean(), nullable=False),
    sa.Column('has_api_access', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_table('store_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=30), nullable=True),
    sa.Column('gateway_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_customer_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=200), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_subscriptions_gateway_subscription_id'), 'store_subscriptions', ['gateway_subscription_id'], unique=False)
    op.create_index(op.f('ix_store_subscriptions_id'), 'store_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_store_subscriptions_store_id'), 'store_subscriptions', ['store_id'], unique=False)
    op.add_column('stores', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column('stores', sa.Column('subscription_status', sa.String(length=20), nullable=False))
    op.add_column('stores', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('stores', sa.Column('subscribed_at', sa.DateTime(), nullable=True))
    op.add_column('stores', sa.Column('razorpay_customer_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_stores_plan_id'), 'stores', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'stores', 'plans', ['plan_id'], ['id'])
    op.drop_index('idx_txn_invoice_number', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_txn_invoice_number', 'transactions', ['invoice_number'], unique=True)
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_index(op.f('ix_stores_plan_id'), table_name='stores')
    op.drop_column('stores', 'razorpay_customer_id')
    op.drop_column('stores', 'subscribed_at')
    op.drop_column('stores', 'trial_ends_at')
    op.drop_column('stores', 'subscription_status')
    op.drop_column('stores', 'plan_id')
    op.drop_index(op.f('ix_store_subscriptions_store_id'), table_name='store_subscriptions')
    op.drop_index(op.f('ix_store_subscriptions_id'), table_name='store_subscriptions')
    op.drop_index(op.f('ix_store_subscriptions_gateway_subscription_id'), table_name='store_subscriptions')
    op.drop_table('store_subscriptions')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
