"""add_loyalty_tables

Revision ID: 421836be84c2
Revises: b3bff35888f8
Create Date: 2026-05-09 20:52:41.751529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421836be84c2'
down_revision: Union[str, None] = 'b3bff35888f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_txn_invoice_number', table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_txn_invoice_number', 'transactions', ['invoice_number'], unique=True)
    # ### end Alembic commands ###
